package com.cro.report.api;
import com.auth0.jwt.JWT; import com.auth0.jwt.algorithms.Algorithm; import com.cro.report.api.ReportDtos.*; import com.cro.report.service.ReportService;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") public class OnlyOfficeController {
 private final ReportService reports; private final String server,secret,publicApi;
 public OnlyOfficeController(ReportService reports,@Value("${app.onlyoffice-public-url:}") String server,@Value("${app.onlyoffice-jwt-secret}") String secret,@Value("${app.public-api-url}") String publicApi){this.reports=reports;this.server=server;this.secret=secret;this.publicApi=publicApi;}
 @GetMapping("/reports/{id}/editor-config") public EditorConfig editor(@PathVariable String id){var r=reports.get(id);if(server.isBlank())return new EditorConfig("",Map.of(),false);var config=new LinkedHashMap<String,Object>();config.put("documentType","word");config.put("document",Map.of("fileType","docx","key",r.id()+"-v"+r.currentVersion(),"title",r.reportNo()+".docx","url",publicApi+"/api/reports/"+id+"/export?format=docx"));config.put("editorConfig",Map.of("callbackUrl",publicApi+"/api/integrations/onlyoffice/callback?reportId="+id,"lang","zh-CN","user",Map.of("id","demo","name","报告操作员")));String token=JWT.create().withPayload(config).sign(Algorithm.HMAC256(secret));config.put("token",token);return new EditorConfig(server,config,true);}
 @PostMapping("/integrations/onlyoffice/callback") public Map<String,Integer> callback(@RequestParam String reportId,@RequestBody Map<String,Object> body){Object status=body.get("status");if(status instanceof Number n && (n.intValue()==2||n.intValue()==6)){/* Production adapter downloads body.url, hashes, stores and creates immutable version. */}return Map.of("error",0);}
 @GetMapping("/reports/{id}/export") public ResponseEntity<byte[]> export(@PathVariable String id,@RequestParam(defaultValue="docx") String format){return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).header("X-Report-Status","Document storage adapter not configured").body(new byte[0]);}
}
