<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Download, Refresh, Search } from '@element-plus/icons-vue'
import { adminApi, type GenerationHistoryItem } from './admin-api'
import ReportGenerationDetail from './ReportGenerationDetail.vue'
defineProps<{ canDownload: boolean }>()
const items=ref<GenerationHistoryItem[]>([]);const total=ref(0);const loading=ref(false);const detail=ref<GenerationHistoryItem>();const filters=reactive({query:'',status:'',page:1,page_size:20,date_from:'',date_to:''})
const reportNo=(row:GenerationHistoryItem)=>String(row.resolved_data?.report_no||'-')
async function load(){loading.value=true;try{const result=await adminApi.reportHistory(filters);items.value=result.items;total.value=result.total}catch(error){console.error('加载报告历史失败',error)}finally{loading.value=false}}
async function openDetail(row:GenerationHistoryItem){try{detail.value=await adminApi.reportHistoryDetail(row.id)}catch(error){console.error('加载生成详情失败',error)}}
function closeDetail(){detail.value=undefined}
function download(row:GenerationHistoryItem){window.location.href=adminApi.reportHistoryDownloadUrl(row.id)}
onMounted(load)
</script>
<template><section v-if="detail" class="history-detail-page"><div class="detail-toolbar"><el-button @click="closeDetail">返回生成历史</el-button><h1>生成记录详情</h1></div><ReportGenerationDetail :detail="detail"/></section><section v-else class="management-page"><header><div><h1>报告生成历史</h1><p>每次生成独立留档，可查看当时版本并下载历史文件</p></div></header><div class="management-toolbar history-filter"><el-input v-model="filters.query" placeholder="报告名称或编号" :prefix-icon="Search" clearable/><el-select v-model="filters.status" clearable placeholder="生成状态"><el-option label="成功" value="SUCCESS"/><el-option label="失败" value="FAILED"/><el-option label="生成中" value="PROCESSING"/></el-select><!-- value-format 带 Z 输出时区偏移，后端按 UTC 时间戳比较；纯本地时间串与存储的 +00:00 串做字符串比较会筛错 -->
<el-date-picker v-model="filters.date_from" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" placeholder="开始时间"/><el-date-picker v-model="filters.date_to" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" placeholder="结束时间"/><el-button :icon="Refresh" @click="load">查询</el-button></div><el-table :data="items" v-loading="loading" height="calc(100vh - 260px)" @row-click="openDetail"><el-table-column prop="title" label="报告名称" min-width="220"/><el-table-column label="报告编号" width="160"><template #default="{row}">{{reportNo(row)}}</template></el-table-column><el-table-column label="版本" width="90"><template #default="{row}">V{{row.version_no||'-'}}</template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}">{{row.generation_context?.phase||'-'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='SUCCESS'?'success':row.status==='FAILED'?'danger':'warning'">{{row.status==='SUCCESS'?'成功':row.status==='FAILED'?'失败':'生成中'}}</el-tag></template></el-table-column><el-table-column prop="display_name" label="生成人" width="120"/><el-table-column prop="generated_at" label="生成时间" width="190"/><el-table-column label="文件" width="90"><template #default="{row}"><el-button v-if="canDownload&&row.status==='SUCCESS'&&row.output_name" link :icon="Download" @click.stop="download(row)">下载</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="filters.page" v-model:page-size="filters.page_size" :total="total" layout="total, prev, pager, next" @change="load"/></section></template>
<style scoped>.history-detail-page{height:100%;overflow:auto;padding:24px 30px;background:#fff}.detail-toolbar{display:flex;align-items:center;gap:16px;margin-bottom:18px}.detail-toolbar h1{margin:0;font-size:20px}</style>
