<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Download, Refresh, Search } from '@element-plus/icons-vue'
import { adminApi, type GenerationHistoryItem } from './admin-api'
const items=ref<GenerationHistoryItem[]>([]);const total=ref(0);const loading=ref(false);const detail=ref<GenerationHistoryItem>();const filters=reactive({query:'',status:'',page:1,page_size:20,date_from:'',date_to:''})
const reportNo=(row:GenerationHistoryItem)=>String(row.resolved_data?.report_no||'-')
async function load(){loading.value=true;try{const result=await adminApi.reportHistory(filters);items.value=result.items;total.value=result.total}finally{loading.value=false}}
function download(row:GenerationHistoryItem){window.location.href=adminApi.reportHistoryDownloadUrl(row.id)}
onMounted(load)
</script>
<template><section class="management-page"><header><div><h1>报告生成历史</h1><p>每次生成独立留档，可查看当时版本并下载历史文件</p></div></header><div class="management-toolbar history-filter"><el-input v-model="filters.query" placeholder="报告名称或编号" :prefix-icon="Search" clearable/><el-select v-model="filters.status" clearable placeholder="生成状态"><el-option label="成功" value="SUCCESS"/><el-option label="失败" value="FAILED"/><el-option label="生成中" value="PROCESSING"/></el-select><el-date-picker v-model="filters.date_from" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="开始时间"/><el-date-picker v-model="filters.date_to" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="结束时间"/><el-button :icon="Refresh" @click="load">查询</el-button></div><el-table :data="items" v-loading="loading" height="calc(100vh - 260px)" @row-click="detail=$event"><el-table-column prop="title" label="报告名称" min-width="220"/><el-table-column label="报告编号" width="160"><template #default="{row}">{{reportNo(row)}}</template></el-table-column><el-table-column label="版本" width="90"><template #default="{row}">V{{row.version_no||'-'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='SUCCESS'?'success':row.status==='FAILED'?'danger':'warning'">{{row.status==='SUCCESS'?'成功':row.status==='FAILED'?'失败':'生成中'}}</el-tag></template></el-table-column><el-table-column prop="display_name" label="生成人" width="120"/><el-table-column prop="generated_at" label="生成时间" width="190"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button v-if="row.status==='SUCCESS'&&row.output_name" link :icon="Download" @click.stop="download(row)">下载</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="filters.page" v-model:page-size="filters.page_size" :total="total" layout="total, prev, pager, next" @change="load"/><el-drawer v-model="detail" title="生成记录详情" size="460"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="报告">{{detail.title}}</el-descriptions-item><el-descriptions-item label="报告编号">{{reportNo(detail)}}</el-descriptions-item><el-descriptions-item label="报告版本">V{{detail.version_no||'-'}}</el-descriptions-item><el-descriptions-item label="生成人">{{detail.display_name||detail.username||'-'}}</el-descriptions-item><el-descriptions-item label="生成时间">{{detail.generated_at}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status}}</el-descriptions-item><el-descriptions-item v-if="detail.error_message" label="失败原因">{{detail.error_message}}</el-descriptions-item></el-descriptions></el-drawer></section></template>
